# https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service

apiVersion: v1
kind: Pod
metadata:
  name: spinderella
spec:
  containers:
  - name: fresco
    image: bali:5000/spinderella
    imagePullPolicy: Always
    ports:
    - name: tcp
      protocol: TCP
      containerPort: 80
